### ISSUE TITLE
Mithril rewrite seems to be broken, due to recent bundler changes?

### ISSUE THREAD

**Issue by Bondifrench** [lhorie/mithril.js#1191]
### Description:

Mithril rewrite appears to be broken, when using rawgit [version](https://rawgit.com/lhorie/mithril.js/rewrite/mithril.js) 
### Steps to Reproduce:
See jsbin with simple [example](http://jsbin.com/xelosoqixi/1/edit?html,js,console,output)

### Expected:

Expected `Test` to appear in Output

### Actual:
Nothing is displayed and in dev tools console:
````
error Script error. (line 0)
VM248 mithril.js:1128 Uncaught ReferenceError: module is not defined(anonymous function) @ VM248 mithril.js:1128(anonymous function) @ VM248 mithril.js:1
runner-3.38.13.min.js:1 error ReferenceError: m is not defined
    at xelosoqixi.js:6:1
VM203 xelosoqixi.js:6 Uncaught ReferenceError: m is not defined
````
When looking at the file, it seems Mithril rewrite is encapsulated in a `new function () { }` which prevents of accessing `m`

**Comment by isiahmeadows** [comment]
[Found the offending commit heuristically](https://github.com/lhorie/mithril.js/commit/49c3376db0a82acfbc5c26c918665df687686ff7), although it's not very useful (it's simply rebuilding the bundle).

**Comment by isiahmeadows** [comment]
It's somewhere between 640b192 and 49c3376.

**Comment by pygy** [comment]
See https://github.com/lhorie/mithril.js/blob/608a494538daede4e16c6e02114e36366d2d49d5/package.json#L11-L12 and the respective `index.js` and `browser.js`.

Right now, `mithril.js` is a CommonJS module, and `mithril.min.js` is intended for direct browser consumption, which is IMO suboptimal since there's no source map in the repo.

I'm a bit puzzled by the bundled CommonJS version.

**Comment by CreaturesInUnitards** [comment]
trivial issue; `mithril.js` isn't attaching `m` to `window`;  replace line 1128 `module.exports = m` with:

`if (typeof module === 'object') {     
	module.exports = m     
} else {     
	window.m = m     
}     
`

**Comment by pygy** [comment]
It's been removed on purpose with the introduction of `browser.js` that's meant to build browser versions.

**Comment by lhorie** [comment]
Ok, so just to give some context to the madness:

I was trying to replace webpack with bundler in my day job project. There were a couple of issues that I ran into that I was trying to solve: 

- having a `module.exports`  expression within a `if` statement in `index.js` was a bit fragile and was causing code mangling if I `require`d `index.js` into a larger project (i.e. `require("mithril")`) and I didn't have wrapping curly brackets
- the bundler was inlining everything into the global scope, which was causing an issue because I have a component called `Map` (which clashes with ES6 Map), hence the `new function() {...}`

The purpose of the exercise was to, well, try to break bundler under a in-the-wild scenario. As it turns out, my day job project has a lot of cases that I think bundler should handle, e.g. requires from dependencies vs from relative paths, global variable assignments from require, clashes with native APIs (both via requiring and local module variables), and so on

It's still a little rough around the edges, so please bear with me.

**Comment by tivac** [comment]
@lhorie Not the choice I'd make, but I admire your can-do attitude.

Would it make sense to break bundler out into it's own project at this point then? Then mithril could depend on a specific revision/version that is stable while you work on `bundler` features/issues that aren't necessary for mithril to function.

**Comment by lhorie** [comment]
Bundler should be fixed now
